#pragma once
#include "src/types.h"

enum {
  kNumberOfAssets = 58
};
extern const uint8 *g_asset_ptrs[kNumberOfAssets];
extern uint32 g_asset_sizes[kNumberOfAssets];
extern MemBlk FindInAssetArray(int asset, int idx);

#define kGraphicsPtrs(idx) FindInAssetArray(0, idx)
#define kGfx32 ((uint8*)g_asset_ptrs[1])
#define kGfx32_SIZE (g_asset_sizes[1])
#define kGfx33 ((uint8*)g_asset_ptrs[2])
#define kGfx33_SIZE (g_asset_sizes[2])
#define kLoadStripeImagePtrs(idx) FindInAssetArray(3, idx)
#define kLayer3ImagePtrs(idx) FindInAssetArray(4, idx)
#define kOverworldLayer2EventTilemap_Tiles ((uint8*)g_asset_ptrs[5])
#define kOverworldLayer2EventTilemap_Tiles_SIZE (g_asset_sizes[5])
#define kSpcCreditsMusicBank ((uint8*)g_asset_ptrs[6])
#define kSpcCreditsMusicBank_SIZE (g_asset_sizes[6])
#define kSpcLevelMusicBank ((uint8*)g_asset_ptrs[7])
#define kSpcLevelMusicBank_SIZE (g_asset_sizes[7])
#define kSpcEngine ((uint8*)g_asset_ptrs[8])
#define kSpcEngine_SIZE (g_asset_sizes[8])
#define kSpcSamples ((uint8*)g_asset_ptrs[9])
#define kSpcSamples_SIZE (g_asset_sizes[9])
#define kSpcOverworldMusicBank ((uint8*)g_asset_ptrs[10])
#define kSpcOverworldMusicBank_SIZE (g_asset_sizes[10])
#define kMap16Data_OverworldLayer1 ((uint16*)g_asset_ptrs[11])
#define kMap16Data_OverworldLayer1_SIZE (g_asset_sizes[11])
#define kkOverworldLayer2EventTilemap_Prop ((uint8*)g_asset_ptrs[12])
#define kkOverworldLayer2EventTilemap_Prop_SIZE (g_asset_sizes[12])
#define kMap16Data ((uint16*)g_asset_ptrs[13])
#define kMap16Data_SIZE (g_asset_sizes[13])
#define kMap16Data_Castle ((uint16*)g_asset_ptrs[14])
#define kMap16Data_Castle_SIZE (g_asset_sizes[14])
#define kMap16Data_Rope ((uint16*)g_asset_ptrs[15])
#define kMap16Data_Rope_SIZE (g_asset_sizes[15])
#define kMap16Data_Underground ((uint16*)g_asset_ptrs[16])
#define kMap16Data_Underground_SIZE (g_asset_sizes[16])
#define kMap16Data_GhostHouse ((uint16*)g_asset_ptrs[17])
#define kMap16Data_GhostHouse_SIZE (g_asset_sizes[17])
#define kGameMode1B_EndingCinema_Tilemaps ((uint8*)g_asset_ptrs[18])
#define kGameMode1B_EndingCinema_Tilemaps_SIZE (g_asset_sizes[18])
#define kGameMode1B_EndingCinema_RowPointers ((uint16*)g_asset_ptrs[19])
#define kGameMode1B_EndingCinema_RowPointers_SIZE (g_asset_sizes[19])
#define kLevelInfo_05F000 ((uint8*)g_asset_ptrs[20])
#define kLevelInfo_05F000_SIZE (g_asset_sizes[20])
#define kLevelInfo_05F200 ((uint8*)g_asset_ptrs[21])
#define kLevelInfo_05F200_SIZE (g_asset_sizes[21])
#define kLevelInfo_05F400 ((uint8*)g_asset_ptrs[22])
#define kLevelInfo_05F400_SIZE (g_asset_sizes[22])
#define kLevelInfo_05F600 ((uint8*)g_asset_ptrs[23])
#define kLevelInfo_05F600_SIZE (g_asset_sizes[23])
#define kLevelInfo_05F800 ((uint8*)g_asset_ptrs[24])
#define kLevelInfo_05F800_SIZE (g_asset_sizes[24])
#define kLevelInfo_05FA00 ((uint8*)g_asset_ptrs[25])
#define kLevelInfo_05FA00_SIZE (g_asset_sizes[25])
#define kLevelInfo_05FC00 ((uint8*)g_asset_ptrs[26])
#define kLevelInfo_05FC00_SIZE (g_asset_sizes[26])
#define kLevelInfo_05FE00 ((uint8*)g_asset_ptrs[27])
#define kLevelInfo_05FE00_SIZE (g_asset_sizes[27])
#define kLoadLevel_DATA_05D608 ((uint8*)g_asset_ptrs[28])
#define kLoadLevel_DATA_05D608_SIZE (g_asset_sizes[28])
#define kDisplayMessage_DATA_05A5D9 ((uint8*)g_asset_ptrs[29])
#define kDisplayMessage_DATA_05A5D9_SIZE (g_asset_sizes[29])
#define kOverworldLightningAndRandomCloudSpawning ((uint8*)g_asset_ptrs[30])
#define kOverworldLightningAndRandomCloudSpawning_SIZE (g_asset_sizes[30])
#define kLevelNames ((uint16*)g_asset_ptrs[31])
#define kLevelNames_SIZE (g_asset_sizes[31])
#define kLoadOverworldLayer2AndEventsTilemaps_OverworldLayer2Tilemap ((uint8*)g_asset_ptrs[32])
#define kLoadOverworldLayer2AndEventsTilemaps_OverworldLayer2Tilemap_SIZE (g_asset_sizes[32])
#define kLoadOverworldLayer2AndEventsTilemaps_OverworldLayer2Tilemap_Prop ((uint8*)g_asset_ptrs[33])
#define kLoadOverworldLayer2AndEventsTilemaps_OverworldLayer2Tilemap_Prop_SIZE (g_asset_sizes[33])
#define kLoadOverworldLayer1AndEvents_DATA_0CF7DF ((uint8*)g_asset_ptrs[34])
#define kLoadOverworldLayer1AndEvents_DATA_0CF7DF_SIZE (g_asset_sizes[34])
#define kLineGuideSpeedTableData ((uint8*)g_asset_ptrs[35])
#define kLineGuideSpeedTableData_SIZE (g_asset_sizes[35])
#define kLevelData_Layer1(idx) FindInAssetArray(36, idx)
#define kEntranceData_Layer1(idx) FindInAssetArray(37, idx)
#define kChoclateIsland2_Layer1(idx) FindInAssetArray(38, idx)
#define kRollCallData_Layer1(idx) FindInAssetArray(39, idx)
#define kLevelData_Layer2(idx) FindInAssetArray(40, idx)
#define kLevelData_Layer2_IsBg ((uint8*)g_asset_ptrs[41])
#define kLevelData_Layer2_IsBg_SIZE (g_asset_sizes[41])
#define kEntranceData_Layer2(idx) FindInAssetArray(42, idx)
#define kEntranceData_Layer2_IsBg ((uint8*)g_asset_ptrs[43])
#define kEntranceData_Layer2_IsBg_SIZE (g_asset_sizes[43])
#define kChoclateIsland2_Layer2(idx) FindInAssetArray(44, idx)
#define kChoclateIsland2_Layer2_IsBg ((uint8*)g_asset_ptrs[45])
#define kChoclateIsland2_Layer2_IsBg_SIZE (g_asset_sizes[45])
#define kRollCallData_Layer2(idx) FindInAssetArray(46, idx)
#define kRollCallData_Layer2_IsBg ((uint8*)g_asset_ptrs[47])
#define kRollCallData_Layer2_IsBg_SIZE (g_asset_sizes[47])
#define kBufferCreditsBackgrounds_Layer2(idx) FindInAssetArray(48, idx)
#define kBufferCreditsBackgrounds_Layer2_IsBg ((uint8*)g_asset_ptrs[49])
#define kBufferCreditsBackgrounds_Layer2_IsBg_SIZE (g_asset_sizes[49])
#define kLoadLevelSpriteList(idx) FindInAssetArray(50, idx)
#define kLoadLevel_SpriteDataPtrs ((uint16*)g_asset_ptrs[51])
#define kLoadLevel_SpriteDataPtrs_SIZE (g_asset_sizes[51])
#define kFileSelectText_EraseFile ((uint8*)g_asset_ptrs[52])
#define kFileSelectText_EraseFile_SIZE (g_asset_sizes[52])
#define kInitializeMode7TilemapsAndPalettes_TilemapData ((uint8*)g_asset_ptrs[53])
#define kInitializeMode7TilemapsAndPalettes_TilemapData_SIZE (g_asset_sizes[53])
#define kLayer2EventData_TileEntries ((uint16*)g_asset_ptrs[54])
#define kLayer2EventData_TileEntries_SIZE (g_asset_sizes[54])
#define kUpdateLevelName_LevelNameStrings ((uint8*)g_asset_ptrs[55])
#define kUpdateLevelName_LevelNameStrings_SIZE (g_asset_sizes[55])
#define kGameMode25_ShowEnemyRollcallScreen_TileData ((uint8*)g_asset_ptrs[56])
#define kGameMode25_ShowEnemyRollcallScreen_TileData_SIZE (g_asset_sizes[56])
#define kRom ((uint8*)g_asset_ptrs[57])
#define kRom_SIZE (g_asset_sizes[57])
#define kAssets_Sig 83, 109, 119, 95, 118, 48, 32, 32, 32, 32, 32, 32, 32, 32, 10, 0, 52, 78, 183, 252, 40, 131, 208, 13, 64, 107, 152, 161, 6, 99, 150, 130, 181, 105, 242, 158, 255, 50, 227, 158, 57, 108, 112, 255, 9, 165, 191, 187
